artifacts_root: artifacts

mongodb:
  uri: "mongodb://username:password@localhost:27017/"
  db_name: "your_database"
  collection_name: "your_collection"

data_ingestion:
  root_dir: artifacts/data_ingestion
  # source_URL: https://enter-dataset-url-here
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion